export type MatchSummary = {
  id: string;
  tournamentId: string;
  stageId: string | null;
  stageType?: "GROUP_STAGE" | "KNOCKOUT_STAGE" | null;
  stageIsPublic?: boolean | null;
  groupId: string | null;
  groupName?: string | null;
  homeTeamId: string | null;
  awayTeamId: string | null;
  homeTeamName: string;
  awayTeamName: string;
  roundLabel: string | null;
  startsAt: Date | null;
  endsAt: Date | null;
  liveStartedAt: Date | null;
  finishedAt: Date | null;
  lastScoreUpdatedAt: Date | null;
  scoreVersion: number;
  locationLabel: string | null;
  status: "SCHEDULED" | "LIVE" | "FINISHED" | "POSTPONED" | "CANCELLED";
  homeScore: number;
  awayScore: number;
};
